name:                servant-http2-client
version:             0.1.0.0
github:              "githubuser/servant-http2-client"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-http2-client#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- data-default-class
- exceptions
- servant
- servant-client-core
- text
- transformers
- mtl
- http2
- http2-client
- http-types
- http-media
- case-insensitive
- tls
- aeson

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  servant-http2-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-http2-client

tests:
  servant-http2-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-http2-client
