name:                servant-http2-client
version:             0.1.0.0
github:              "lucasdicioccio/servant-http2-client"
license:             BSD3
author:              "Lucas DiCioccio"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018 Lucas DiCioccio"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generate HTTP2 clients from Servant API descriptions.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-http2-client#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- case-insensitive
- containers
- exceptions
- http2
- http2-client
- http-media
- http-types
- mtl
- servant-client-core
- text
- transformers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  servant-http2-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - async
    - data-default-class
    - servant
    - servant-http2-client
    - servant-client-core
    - tls

tests:
  servant-http2-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - async
    - data-default-class
    - servant
    - servant-http2-client
    - servant-client-core
    - tls
